### ISSUE TITLE
UHU-3 ?

### ISSUE THREAD

**Issue by attuska** [uhulinux/cdgen-ubk#1]
Ez a mostani változat csak a leendő kiadáshoz használható, UHU-3 -hoz isó a fájlok utólagos és helyes megváltoztatása nélkül nem, mivel az alap csomaglistákban az illető célrendszerhez már nem elérhető csomagok vannak. Nem beszélve a sources.list kavarról sem, meg arról, hogy a 2.2-UBK isó generáláshoz már végképp nem jó.
Egyszerűbb lenne szerintem inkább teljesen különválasztani az UHU-3, UHU-2.2 és UHU-leendő isó generáláshoz a szkript és dataegyüttest (brach), ahelyett, hogy feltételrendszereket kellne belerakni a szkriptekbe.

**Comment by rezso** [comment]
Nem is volt cél, hogy minden UHU kiadást kezeljen.
Most nyilván a dev ágra van kiélezve, de a csomaglisták és a sources.list módosításával jó a 3-hoz is.
A 2.2-höz pedig talán az eredeti cdgen a jó.

**Comment by attuska** [comment]
Esetleg archiválni a 3-hoz jó listákat?

**Comment by rezso** [comment]
Felesleges. Ami változás van, az bőven elfér egy kis szöveges fájlban, a sources.list-nél pedig úgyis az az alap, amit az apt szállít.
