### ISSUE TITLE
iso DIST variable

### ISSUE THREAD

**Issue by attuska** [uhulinux/cdgen-ubk#5]
./40-prepare-dvd: line 15: DIST: unbound variable
    data/UHU3/packages-cd-base.txt lvm van, ami a dev tárolóban nincs.

**Comment by rezso** [comment]
Mivel a cdgen nem kezeli külön a dev tárolót, ezzel nem foglalkozunk.

**Comment by attuska** [comment]
A dev tárolót az értem, az rendben is van, hogy azzal nem foglalkozunk.

Ettől még DIST változó definiálatlansága még fennáll, az indító cdgen szkriptben mintha nem kapna értéket a $1 paraméter nélkül, vagy nem adja át a 40-prepare-dvd szkriptnek.

> if [ -n "$1" ]; then
	if [ "$1" == "--help" ];then
		hiba
	else
		DIST=$1
		if [ ! -d data/$DIST ];then
			hiba "Csak UBK1|UBK2|UBK3 lehet az UHU_RELEASE értéke, ami most $DIST!"
		else
			rm -f UHU_RELEASE
			echo "$1" > UHU_RELEASE
		fi
    fi
fi
>

> DIST=$(cat UHU_RELEASE)

**Comment by rezso** [comment]
Az viszont nem UBK3/dev specifikus hiba. Amúgy pedig az egész opciókezelést átírtam már a cdgen scriptben, csak commitolva nincs még.

**Comment by attuska** [comment]
https://github.com/uhulinux/cdgen-ubk/commit/4e93e3b712e83633e6355fd9c480b891663d321a
